/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package network;

/**
 *
 * @author บักคุณท่าน เพ้ง อิอิ
 */
public class ProjectRouter extends javax.swing.JFrame {

    /**
     * Creates new form ProjectRouter
     */
    public ProjectRouter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PING = new javax.swing.JButton();
        STOP = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        cmd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        Router = new javax.swing.JButton();
        PC1 = new javax.swing.JButton();
        PC2 = new javax.swing.JButton();
        PINGING = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("router simulation");
        setAutoRequestFocus(false);
        setName("uuuu"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PING.setText("PING");
        PING.setToolTipText("");
        getContentPane().add(PING, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 127, 32));

        STOP.setText("CLEAR IP");
        getContentPane().add(STOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 127, 31));

        RESET.setText("CLEAR STATUS");
        getContentPane().add(RESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 127, 32));

        cmd.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        cmd.setToolTipText("test");
        cmd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmd.setName("tttt"); // NOI18N
        cmd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(0, 255, 0));

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 255, 0));
        jTextArea1.setRows(99);
        jScrollPane1.setViewportView(jTextArea1);

        cmd.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 120));

        getContentPane().add(cmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 310, 160));
        cmd.getAccessibleContext().setAccessibleName("status");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "simulator"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Router.setIcon(new javax.swing.ImageIcon(getClass().getResource("/network/router resize.png"))); // NOI18N
        Router.setText("ROUTER");
        jPanel2.add(Router, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        PC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/network/PC resize2.png"))); // NOI18N
        PC1.setText("PC1");
        jPanel2.add(PC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        PC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/network/PC resize2.png"))); // NOI18N
        PC2.setText("PC2");
        jPanel2.add(PC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 390, 250));

        PINGING.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ping"));
        PINGING.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PC1", "PC2" }));
        PINGING.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 210, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PC1", "PC2" }));
        PINGING.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 210, -1));

        jLabel5.setText("from :");
        PINGING.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel6.setText("to :");
        PINGING.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        getContentPane().add(PINGING, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 310, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectRouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectRouter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PC1;
    private javax.swing.JButton PC2;
    private javax.swing.JButton PING;
    private javax.swing.JPanel PINGING;
    private javax.swing.JButton RESET;
    private javax.swing.JButton Router;
    private javax.swing.JButton STOP;
    private javax.swing.JPanel cmd;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
